services:
  glpi:
    image: ${IMAGE_REPOSITORY:-localhost/glpi}:${IMAGE_TAG:-latest}
    build:
      context: .
      x-bake:
        output: type=${IMAGE_OUTPUT_TYPE:-docker}
        tags:
        - ${IMAGE_REPOSITORY:-localhost/glpi}:${IMAGE_TAG:-latest}
    environment:
      DB_HOST: db
      DB_USER: glpi
      DB_DATABASE: glpi
      DB_PASSWORD: glpi
      DEFAULT_LANGUAGE: en_GB
    volumes:
    - glpi_marketplace:/var/www/glpi/marketplace
    - glpi_files:/var/www/glpi/files
    ports:
    - 80:80

  db:
    image: mariadb
    command: --skip-grant-tables
    restart: always
    environment:
      MYSQL_USER: glpi
      MYSQL_PASSWORD: glpi
      MYSQL_DATABASE: glpi
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3306:3306
    volumes:
    - mariadb:/var/lib/mysql

volumes:
  glpi_marketplace:
  glpi_files:
  mariadb:
